In [16]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense,Bidirectional,LSTM,Conv2D
from tensorflow.keras.optimizers import RMSprop

In [17]:
a=pd.read_csv('train_data.csv')
a.head()

Unnamed: 0        Date  Close/Last    Volume    Open    High       Low
0           0  2020-05-22      318.89  20450750  315.77  319.23  315.3500
1           1  2020-05-21      316.85  25672210  318.66  320.89  315.8700
2           2  2020-05-20      319.23  27876220  316.68  319.52  316.2000
3           3  2020-05-19      313.14  25432390  315.03  318.52  313.0100
4           4  2020-05-18      314.96  33843130  313.17  316.50  310.3241

In [18]:

y=a[['Open']]
y_train=np.array(y)


In [19]:

y_train

array([[315.77  ],
       [318.66  ],
       [316.68  ],
       [315.03  ],
       [313.17  ],
       [300.35  ],
       [304.51  ],
       [312.15  ],
       [317.83  ],
       [308.1   ],
       [305.64  ],
       [303.22  ],
       [300.46  ],
       [295.06  ],
       [289.17  ],
       [286.25  ],
       [289.96  ],
       [284.73  ],
       [285.08  ],
       [281.8   ],
       [277.2   ],
       [275.87  ],
       [273.61  ],
       [276.28  ],
       [277.95  ],
       [284.69  ],
       [287.38  ],
       [282.4   ],
       [280.    ],
       [268.31  ],
       [268.7   ],
       [262.74  ],
       [270.8   ],
       [250.9   ],
       [242.8   ],
       [240.34  ],
       [246.5   ],
       [255.6   ],
       [250.74  ],
       [252.75  ],
       [246.52  ],
       [250.75  ],
       [236.36  ],
       [228.08  ],
       [247.18  ],
       [247.385 ],
       [239.77  ],
       [247.51  ],
       [241.95  ],
       [264.89  ],
       [255.94  ],
       [277.39  ],
       [277.

In [20]:

from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(0, 1))
y = sc.fit_transform(y_train)

In [22]:
y.shape

(1000, 1)

In [32]:
x_train = []
y_train = []

for i in range(60, 1000):
  x_train.append(y[i-60:i, 0])
  y_train.append(y[i, 0])

X_train, y_train = np.array(x_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X_train)
print(y_train)

[[[0.96130952]
  [0.97377502]
  [0.96523464]
  ...
  [0.90911836]
  [0.81685645]
  [0.7089372 ]]

 [[0.97377502]
  [0.96523464]
  [0.95811767]
  ...
  [0.81685645]
  [0.7089372 ]
  [0.81176674]]

 [[0.96523464]
  [0.95811767]
  [0.95009489]
  ...
  [0.7089372 ]
  [0.81176674]
  [0.83518806]]

 ...

 [[0.05503796]
  [0.05564182]
  [0.05917874]
  ...
  [0.02428399]
  [0.02415459]
  [0.02639752]]

 [[0.05564182]
  [0.05917874]
  [0.06258627]
  ...
  [0.02415459]
  [0.02639752]
  [0.02738958]]

 [[0.05917874]
  [0.06258627]
  [0.0625    ]
  ...
  [0.02639752]
  [0.02738958]
  [0.0219548 ]]]
[8.11766736e-01 8.35188061e-01 8.97386128e-01 8.81469979e-01
 9.73602484e-01 9.90898896e-01 9.79554865e-01 9.59541063e-01
 1.00000000e+00 9.97627674e-01 9.85895445e-01 9.95082816e-01
 9.54451346e-01 9.89777433e-01 9.90640097e-01 9.94737750e-01
 9.59325397e-01 9.11835749e-01 9.83566253e-01 9.81901311e-01
 9.98749137e-01 9.47636301e-01 9.36680469e-01 9.80633195e-01
 9.70583161e-01 9.73429952e-01 9.6743443