In [2]:
import tensorflow as tf 
import numpy as np
import matplotlib.pyplot as plt 
from tensorflow.data import Dataset

In [4]:
d=Dataset.range(10)
for i in d:
  print(i.numpy())

0
1
2
3
4
5
6
7
8
9


In [9]:
d=Dataset.range(10)
d=d.window(5,shift=1)
for i in d:
  for j in i:
    print(j.numpy(),end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [10]:
d=Dataset.range(10)
d=d.window(5,shift=1,drop_remainder=True)
for i in d:
  for j in i:
    print(j.numpy(),end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [13]:
d=Dataset.range(10)
d=d.window(5,shift=1,drop_remainder=True)
d=d.flat_map(lambda i:i.batch(5))
for i in d:
  print(i.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [14]:
d=Dataset.range(10)
d=d.window(5,shift=1,drop_remainder=True)
d=d.flat_map(lambda i:i.batch(5))
d=d.map(lambda i:(i[:-1],i[-1:]))
for i,j in d:
  print(i.numpy(),j.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [16]:
d=Dataset.range(10)
d=d.window(5,shift=1,drop_remainder=True)
d=d.flat_map(lambda i:i.batch(5))
d=d.map(lambda i:(i[:-1],i[-1:]))
d=d.shuffle(buffer_size=10)
d=d.batch(2).prefetch(1)
for i,j in d:
  print(i.numpy(),j.numpy())

[[1 2 3 4]
 [5 6 7 8]] [[5]
 [9]]
[[2 3 4 5]
 [4 5 6 7]] [[6]
 [8]]
[[3 4 5 6]
 [0 1 2 3]] [[7]
 [4]]
