In [2]:
import numpy as np 
import pandas as pd

from sklearn  import preprocessing

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

a=pd.read_csv("loan_train.csv")

a.head()
a['due_date'] = pd.to_datetime(a['due_date'])
a['effective_date'] = pd.to_datetime(a['effective_date'])
a[['effective_date', 'due_date']].head(3)
a['dayofweek'] = a['effective_date'].dt.dayofweek # Monday:0, Sunday:6a
a.head(3)
a['weekend'] = a['dayofweek'].apply(lambda x: 1 if (x>3)  else 0)
a.head()

user_id  Un_named loan_status  Principal  terms effective_date   due_date  \
0        0         0     PAIDOFF       1000     30     2016-09-08 2016-10-07   
1        2         2     PAIDOFF       1000     30     2016-09-08 2016-10-07   
2        3         3     PAIDOFF       1000     15     2016-09-08 2016-09-22   
3        4         4     PAIDOFF       1000     30     2016-09-09 2016-10-08   
4        6         6     PAIDOFF       1000     30     2016-09-09 2016-10-08   

   age             education  Gender  dayofweek  weekend  
0   45  High School or Below    male          3        0  
1   33              Bechalor  female          3        0  
2   27               college    male          3        0  
3   28               college  female          4        1  
4   29               college    male          4        1

In [3]:
df=a[['Principal','terms','age','education','Gender','dayofweek','weekend']].values
df

array([[1000, 30, 45, ..., 'male', 3, 0],
       [1000, 30, 33, ..., 'female', 3, 0],
       [1000, 15, 27, ..., 'male', 3, 0],
       ...,
       [800, 15, 39, ..., 'male', 0, 0],
       [1000, 30, 28, ..., 'male', 0, 0],
       [1000, 30, 26, ..., 'male', 0, 0]], dtype=object)

In [4]:
df[:,4]=preprocessing.LabelEncoder().fit(['male', 'female']).transform(df[:,4])

In [5]:
df[:,3]=preprocessing.LabelEncoder().fit(['High School or Below','Bechalor','college','Master or Above']).transform(df[:,3])


In [6]:
y=a[['loan_status']]
y=preprocessing.LabelEncoder().fit(['COLLECTION', 'PAIDOFF']).transform(y)

C:\Python\Python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [7]:
x11,x21,y11,y21=train_test_split(df,y,test_size=0.2,random_state=4)
y11
x21

array([[1000, 30, 30, 1, 1, 6, 1],
       [800, 15, 30, 3, 1, 6, 1],
       [1000, 15, 31, 1, 1, 0, 0],
       [1000, 30, 24, 3, 1, 0, 0],
       [1000, 30, 34, 3, 1, 0, 0],
       [1000, 15, 27, 1, 1, 0, 0],
       [1000, 30, 36, 1, 1, 6, 1],
       [1000, 30, 40, 1, 1, 5, 1],
       [1000, 30, 24, 3, 1, 0, 0],
       [1000, 15, 20, 3, 1, 6, 1],
       [1000, 30, 26, 3, 1, 0, 0],
       [1000, 30, 30, 3, 1, 6, 1],
       [500, 15, 23, 3, 0, 0, 0],
       [1000, 30, 27, 1, 1, 0, 0],
       [1000, 15, 45, 1, 1, 6, 1],
       [1000, 7, 26, 0, 0, 0, 0],
       [1000, 30, 22, 1, 1, 6, 1],
       [1000, 15, 30, 3, 1, 0, 0],
       [1000, 30, 28, 3, 1, 4, 1],
       [1000, 30, 37, 1, 1, 2, 0],
       [1000, 30, 33, 3, 0, 6, 1],
       [1000, 30, 31, 3, 1, 6, 1],
       [1000, 30, 26, 1, 1, 6, 1],
       [1000, 30, 24, 1, 0, 6, 1],
       [900, 7, 26, 3, 0, 5, 1],
       [1000, 30, 28, 1, 1, 6, 1],
       [1000, 30, 27, 1, 1, 6, 1],
       [800, 15, 46, 1, 0, 6, 1],
       [1000, 30, 27, 3, 1

decision tree

In [8]:
from sklearn.tree import DecisionTreeClassifier

d=DecisionTreeClassifier(criterion='entropy',max_depth=4)

d.fit(x11,y11)

z=d.predict(x21)

from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score


fs2=f1_score(z,y21, average='weighted')
fs1=jaccard_score(z,y21)
fs1


0.5714285714285714

In [9]:
b=pd.read_csv("loan_test.csv")
b['due_date'] = pd.to_datetime(b['due_date'])
b['effective_date'] = pd.to_datetime(b['effective_date'])
b[['effective_date', 'due_date']].head(3)
b['dayofweek'] = b['effective_date'].dt.dayofweek # Monday:0, Sunday:6a
b.head(3)
b['weekend'] = b['dayofweek'].apply(lambda x: 1 if (x>3)  else 0)
b.head()
dd=b[['Principal','terms','age','education','Gender','dayofweek','weekend']].values
dd[:,4]=preprocessing.LabelEncoder().fit(['male', 'female']).transform(dd[:,4])
dd[:,3]=preprocessing.LabelEncoder().fit(['High School or Below','Bechalor','college','Master or Above']).transform(dd[:,3])
y_1=b[['loan_status']].values
y_1 = np.where(y_1 =='PAIDOFF', 1,0 )
z1=d.predict(dd)
fs2=f1_score(z1,y_1, average='weighted')
fs1=jaccard_score(z1,y_1)
fs1
print(fs2)
print(fs1)


0.731359649122807
0.6888888888888889


logistic regression

In [10]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.01, solver="liblinear").fit(x11,y11)

yhat = LR.predict(x21)
yhat_prob = LR.predict_proba(x21)

#Evaluation
from sklearn.metrics import jaccard_score
jaccard_score(y21,yhat)


0.7428571428571429

In [11]:
b=pd.read_csv("loan_test.csv")
b['due_date'] = pd.to_datetime(b['due_date'])
b['effective_date'] = pd.to_datetime(b['effective_date'])
b[['effective_date', 'due_date']].head(3)
b['dayofweek'] = b['effective_date'].dt.dayofweek # Monday:0, Sunday:6a
b.head(3)
b['weekend'] = b['dayofweek'].apply(lambda x: 1 if (x>3)  else 0)
b.head()
dd=b[['Principal','terms','age','education','Gender','dayofweek','weekend']].values
dd[:,4]=preprocessing.LabelEncoder().fit(['male', 'female']).transform(dd[:,4])
dd[:,3]=preprocessing.LabelEncoder().fit(['High School or Below','Bechalor','college','Master or Above']).transform(dd[:,3])
dd=b[['Principal','terms','age','education','Gender','dayofweek','weekend']].values
dd[:,4]=preprocessing.LabelEncoder().fit(['male', 'female']).transform(dd[:,4])
dd[:,3]=preprocessing.LabelEncoder().fit(['High School or Below','Bechalor','college','Master or Above']).transform(dd[:,3])
y_1=b[['loan_status']].values
y_1 = np.where(y_1 =='PAIDOFF', 1,0 )
z1=LR.predict(dd)
fs2=f1_score(z1,y_1, average='weighted')
fs1=jaccard_score(z1,y_1)
print(fs2)
print(fs1)

0.8467542811628833
0.7547169811320755


support vector machine

In [12]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(x11,y11)

yhat = clf.predict(x21) 


from sklearn.metrics import classification_report, confusion_matrix

from sklearn.metrics import f1_score
print(f1_score(y21, yhat, average='weighted') )


from sklearn.metrics import jaccard_score
print(jaccard_score(y21, yhat))

0.6914285714285714
0.7857142857142857


In [13]:
b=pd.read_csv("loan_test.csv")
b['due_date'] = pd.to_datetime(b['due_date'])
b['effective_date'] = pd.to_datetime(b['effective_date'])
b[['effective_date', 'due_date']].head(3)
b['dayofweek'] = b['effective_date'].dt.dayofweek # Monday:0, Sunday:6a
b.head(3)
b['weekend'] = b['dayofweek'].apply(lambda x: 1 if (x>3)  else 0)
b.head()
dd=b[['Principal','terms','age','education','Gender','dayofweek','weekend']].values
dd[:,4]=preprocessing.LabelEncoder().fit(['male', 'female']).transform(dd[:,4])
dd[:,3]=preprocessing.LabelEncoder().fit(['High School or Below','Bechalor','college','Master or Above']).transform(dd[:,3])
y_1=b[['loan_status']].values
y_1 = np.where(y_1 =='PAIDOFF', 1,0 )
z1=clf.predict(dd)
fs2=f1_score(z1,y_1, average='weighted')
fs1=jaccard_score(z1,y_1)
print(fs2)
print(fs1)

0.851063829787234
0.7407407407407407


KNN

In [14]:
k = 1
e1={}
a=pd.read_csv("loan_train.csv")
a['due_date'] = pd.to_datetime(a['due_date'])
a['effective_date'] = pd.to_datetime(a['effective_date'])
a[['effective_date', 'due_date']].head(3)
a['dayofweek'] = a['effective_date'].dt.dayofweek # Monday:0, Sunday:6a
a.head(3)
a['weekend'] = a['dayofweek'].apply(lambda x: 1 if (x>3)  else 0)
df=a[['Principal','terms','age','education','Gender','dayofweek','weekend']].values
df[:,4]=preprocessing.LabelEncoder().fit(['male', 'female']).transform(df[:,4])
df[:,3]=preprocessing.LabelEncoder().fit(['High School or Below','Bechalor','college','Master or Above']).transform(df[:,3])
print(df)
y=a[['loan_status']].values
y=preprocessing.LabelEncoder().fit(['COLLECTION', 'PAIDOFF']).transform(y)
print(y)
x11,x21,y11,y21=train_test_split(df,y,test_size=0.2,random_state=4)
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
def kfinder(k):
    neigh = KNeighborsClassifier(n_neighbors = k).fit(x11,y11)
    yhat = neigh.predict(x21)
    x2=metrics.accuracy_score(y21, yhat)
    return x2
while(k!=14):
        e1[k]=(kfinder(k))
        k=k+1
print(e1)
all_values = e1.values()
max_value = max(all_values)
print(list(e1.keys())[list(e1.values()).index(max_value)])

[[1000 30 45 ... 1 3 0]
 [1000 30 33 ... 0 3 0]
 [1000 15 27 ... 1 3 0]
 ...
 [800 15 39 ... 1 0 0]
 [1000 30 28 ... 1 0 0]
 [1000 30 26 ... 1 0 0]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
{1: 0.7, 2: 0.6857142857142857, 3: 0.7142857142857143, 4: 0.6714285714285714, 5: 0.7571428571428571, 6: 0.6428571428571429, 7: 0.7, 8: 0.64285714285

C:\Python\Python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [15]:
b=pd.read_csv("loan_test.csv")
b['due_date'] = pd.to_datetime(b['due_date'])
b['effective_date'] = pd.to_datetime(b['effective_date'])
b[['effective_date', 'due_date']].head(3)
b['dayofweek'] = b['effective_date'].dt.dayofweek # Monday:0, Sunday:6a
b.head(3)
b['weekend'] = b['dayofweek'].apply(lambda x: 1 if (x>3)  else 0)
b.head()
dd=b[['Principal','terms','age','education','Gender','dayofweek','weekend']].values
dd[:,4]=preprocessing.LabelEncoder().fit(['male', 'female']).transform(dd[:,4])
dd[:,3]=preprocessing.LabelEncoder().fit(['High School or Below','Bechalor','college','Master or Above']).transform(dd[:,3])
y_1=b[['loan_status']].values
y_1 = np.where(y_1 =='PAIDOFF', 1,0 )
neigh = KNeighborsClassifier(n_neighbors = k).fit(x11,y11)
yhat = neigh.predict(dd)
x2=metrics.accuracy_score(yhat,y_1)
print(fs2)
print(fs1)

0.851063829787234
0.7407407407407407
